<h4><?php echo $detalle_curso->glosa ?></h4>
<div class="horario">
    <ul id="bloques">
        <li class="hdia"><h5>&nbsp;</h5></li>
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
        <li>6</li>
        <li>7</li>
        <li>8</li>
        <li>9</li>
    </ul>
    <?php
    foreach ($nombre_dias as $dia) {
        echo <<<PQR
<ul>
    <li class="hdia"><h5>{$dia}</h5></li>
PQR;
        foreach ($numero_bloques as $bloque) {
            $asignatura = isset($asignaturas[$dia][$bloque]['asignatura']) ? $asignaturas[$dia][$bloque]['asignatura'] : '-';
            $profesor = isset($asignaturas[$dia][$bloque]['profesor']) ? $asignaturas[$dia][$bloque]['profesor'] : '-';
            echo <<<PQR
<li>
    <p><b>{$asignatura}</b></p>
    <span>{$profesor}</span>
</li>
PQR;
        }
        echo '</ul>';
    }
    ?>
</div>
